# Generated by Django 5.2.7 on 2025-11-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_covers/'),
        ),
    ]
