# Generated by Django 5.2.7 on 2025-12-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
