# Generated by Django 5.2.7 on 2025-12-11 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_task_options_task_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
