# Generated by Django 5.2.7 on 2025-12-11 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_starred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('bg-red-500', 'สีแดง (Red)'), ('bg-orange-500', 'สีส้ม (Orange)'), ('bg-yellow-400', 'สีเหลือง (Yellow)'), ('bg-green-500', 'สีเขียว (Green)'), ('bg-blue-500', 'สีฟ้า (Blue)'), ('bg-indigo-500', 'สีม่วง (Indigo)'), ('bg-pink-500', 'สีชมพู (Pink)'), ('bg-gray-500', 'สีเทา (Gray)')], default='bg-blue-500', max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='board.board')),
            ],
        ),
    ]
