# Generated by Django 5.2.7 on 2025-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
