# Generated by Django 5.2.7 on 2025-12-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='board.board'),
        ),
    ]
