# Generated by Django 5.2.7 on 2026-01-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_task_completed_at_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='discord_webhook_url',
            field=models.URLField(blank=True, help_text='วางลิงก์ Webhook จาก Discord Channel ที่ต้องการให้แจ้งเตือน', null=True, verbose_name='Discord Webhook URL'),
        ),
    ]
