# Generated by Django 5.2.7 on 2026-01-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='ID อ้างอิงจาก Google Calendar', max_length=255, null=True, unique=True),
        ),
    ]
