# Generated by Django 5.2.7 on 2026-01-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_task_google_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
