# Generated by Django 5.2.7 on 2026-02-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_alter_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reminded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='remind_days',
            field=models.IntegerField(choices=[(0, 'ไม่แจ้งเตือน'), (1, 'ล่วงหน้า 1 วัน'), (2, 'ล่วงหน้า 2 วัน'), (3, 'ล่วงหน้า 3 วัน'), (7, 'ล่วงหน้า 1 สัปดาห์')], default=1, verbose_name='แจ้งเตือนล่วงหน้า'),
        ),
    ]
